この本、思ったよりも分厚いわね……。なんだか眠くなってきちゃったわ……ふぁああっ……	This book, I'll chunky than I thought .... I've becoming somewhat sleepy ...... Faa there ......
あぁ、ダメ……。もうアタシ……すぅ、すぅ……はうっ……んぅっ……	Oh, no good .... Another Atashi ...... Suu, Suu ...... is Ugh ...... Nu' ......
はぅう、すぅ……ん？　あれ……ご主人様？　これは、夢……？　どうして、ここにご主人様が……	Hau cormorants, N Suu ...? There ...... your husband like? This is a dream ...? Why, your husband like is ...... here
え……？　あ、本当にご主人様……！　やだ、アタシ、寝顔見られた……！？	Huh……? Oh, really your husband like ...! Yada, Atashi, sleeping face seen ...! ?
うぅう……。ど、どうして起こしてくれないのよ、ご主人様……！	It intends UU ....... Etc., gonna do me why cause, your husband like ...!
そ、それはそうだけど……。もう、アタシのバカバカ、どうしてこんなところで寝ちゃうのよ、もう……。	Its, but it's so .... The other, Bakabaka of Atashi, why gonna fall asleep in a place like this, and the other ....
え？　可愛いだなんて……。その、ご主人様……それ、本当？　アタシ、変な顔してなかった？	Huh? ...... Nante's cute. That, your husband like ...... it, true? Atashi, was not a strange face?
そ、そう？　それなら、その……アタシは別にいいんだけど……。	Its, so? Well, I that ... Atashi'm apart from good .......
ええ、わかったわ、ご主人様。うたた寝して風邪でも引いたら、お仕事に差し障りがあるからね。	Yeah, I was found, her husband like. Once you also caught a cold taking a nap, I because there is offense to your work.