……え、嘘、こ、こんな事までするの……？　でもこれって、うぅ……じゃあアタシも……？	... For example, ... to to lie, this, this? But this I, UU ...... Well then Atashi also ...?
えっ！？　だ、誰……って、なんだ、ご主人様か……	eh! ? I, who ...... What, What, your husband like or ......
別にどうもしてないわよ。だ、だから……さっさとあっち行きなさいよ。	Apart from I do not have very much. It, So ...... please quickly over there to go.
え？　あ、あの、これは……！　えっと……その、ううっ……	Huh? Oh, that, this is ...! Well ...... that, Uu' ......
どうしてって……べ、勉強の為よ！　アタシもメイドなんだし、こういった知識も必要でしょ。	...... Downy me why, because of the study! Atashi also to'm a maid, you might also need these knowledge.
なに言ってるのよ、ご主人様！　アタシが、そ、その……淫乱なメイドって言いたいわけ？	What are you saying, my master! Atashi is, its, not want to say I that ...... horny maid?
さ、最低、ご主人様……！　この変態、エッチ……もう、早くどこか行ってよ！	Is, at least, my master ...! This transformation, etch ...... another, go early somewhere!
どうしてちょっとニヤけてるのよ、ご主人様……！　うぅ、もうイヤぁ……	Why gonna have a little only Niya, my master ...! UU, another Well ......